import { h } from '../lib/helpers';

export interface TurboSeriesView {
  anime_id:number; episode_count:number; source_count:number; title:string; image:string;
  totalEps:number; status:string; type:string;
}
export interface TurboEpisodeView { episode_num:number; source_count:number; sources:string; updated_at:string; }

export function renderTurboVidAdmin(o:{
  siteUrl:string; series:TurboSeriesView[]; selected:TurboSeriesView|null;
  episodes:TurboEpisodeView[]; selectedAnime:number;
}):string {
  const {siteUrl,series,selected,episodes,selectedAnime}=o;
  const cards=series.map(s=>{
    const total=Number(s.totalEps||0), uploaded=Number(s.episode_count||0);
    const pct=total?Math.min(100,Math.round(uploaded/total*100)):100;
    return `<a class="tv-folder" href="${siteUrl}/admin/turbovid_servers.php?anime=${s.anime_id}">
      <div class="tv-folder-art">${s.image?`<img src="${h(s.image)}" alt="" loading="lazy">`:''}</div>
      <div class="tv-folder-body"><div class="tv-folder-top"><span class="tv-folder-id">MAL #${s.anime_id}</span><span class="tv-folder-chevron">›</span></div>
      <div class="tv-folder-title">${h(s.title)}</div><div class="tv-folder-meta">${s.type?`<span class="tv-pill">${h(s.type)}</span>`:''}${s.status?`<span class="tv-pill">${h(s.status)}</span>`:''}<span class="tv-pill">${s.source_count} sources</span></div>
      <div class="tv-progress"><div class="tv-progress-head"><span>Episodes</span><span>${String(uploaded).padStart(2,'0')}/${total||'?'}</span></div><div class="tv-track"><i style="width:${pct}%"></i></div></div></div></a>`;
  }).join('');

  const epRows=episodes.map(ep=>`<tr class="tv-ep-row" data-episode="${ep.episode_num}" data-tv-expand="1">
    <td><button class="tv-ep-toggle" type="button" aria-label="Expand episode" data-tv-expand="1">›</button><strong>EP ${ep.episode_num}</strong></td>
    <td>${ep.source_count}</td>
    <td><div class="tv-sources">${String(ep.sources||'').split(' | ').map(x=>`<span class="tv-source">${h(x)}</span>`).join('')}</div></td>
    <td class="tv-date">${h(ep.updated_at||'—')}</td>
  </tr><tr class="tv-ep-details" id="tv-ep-details-${ep.episode_num}" hidden><td colspan="4"><div class="tv-ep-detail-inner"><div class="tv-detail-loading">Loading sources…</div><div class="tv-source-actions"><button class="tv-add-ep-small" type="button" data-tv-add-episode="${ep.episode_num}">＋ Add another source</button></div></div></td></tr>`).join('');

  return `<style>
.tv-page{max-width:1400px;margin:0 auto;padding-bottom:2rem}.tv-hero{margin-bottom:1.15rem}.tv-hero h1{margin:0;font-size:clamp(1.35rem,2.5vw,2rem)}.tv-hero p{margin:.35rem 0 0;color:var(--text-muted);font-size:.88rem}
.tv-add{border:1px solid rgba(124,58,237,.35);background:linear-gradient(135deg,rgba(124,58,237,.16),rgba(20,22,31,.92));border-radius:18px;padding:1rem 1.05rem;margin-bottom:1.25rem;box-shadow:0 12px 30px rgba(0,0,0,.18)}.tv-add-inner{display:flex;align-items:center;justify-content:space-between;gap:1rem}.tv-add-copy{display:flex;align-items:center;gap:.85rem}.tv-add-icon{width:44px;height:44px;border-radius:13px;display:grid;place-items:center;background:rgba(124,58,237,.2);border:1px solid rgba(124,58,237,.3);font-size:1.3rem}.tv-add-title{font-weight:800}.tv-add-sub{color:var(--text-muted);font-size:.78rem;margin-top:2px}.tv-add-btn,.tv-save{border:0;border-radius:11px;padding:.68rem .95rem;background:linear-gradient(135deg,#7c3aed,#9333ea);color:#fff;font-weight:800;cursor:pointer;white-space:nowrap}
.tv-section-head{display:flex;justify-content:space-between;gap:1rem;margin:1.35rem 0 .75rem}.tv-section-head h2{margin:0;font-size:1rem}.tv-section-head span{color:var(--text-muted);font-size:.78rem}.tv-folders{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:1rem}
.tv-folder{display:flex;min-height:190px;overflow:hidden;border:1px solid var(--border);border-radius:18px;background:linear-gradient(145deg,rgba(255,255,255,.045),rgba(13,15,22,.96));text-decoration:none;color:inherit;transition:.18s}.tv-folder:hover{transform:translateY(-3px);border-color:rgba(124,58,237,.55);box-shadow:0 16px 32px rgba(0,0,0,.24)}.tv-folder-art{width:112px;flex:0 0 112px;background:#111;overflow:hidden}.tv-folder-art img{width:100%;height:100%;object-fit:cover}.tv-folder-body{padding:1rem;min-width:0;display:flex;flex:1;flex-direction:column}.tv-folder-top,.tv-progress-head{display:flex;align-items:center;justify-content:space-between;gap:.5rem}.tv-folder-id{font-size:.68rem;color:var(--text-muted);font-family:monospace}.tv-folder-chevron{color:#a78bfa;font-size:1.15rem}.tv-folder-title{font-size:1rem;font-weight:800;line-height:1.2;margin:.45rem 0 .35rem;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.tv-folder-meta,.tv-sources{display:flex;gap:.4rem;flex-wrap:wrap}.tv-pill{border:1px solid var(--border);border-radius:999px;padding:.22rem .48rem;color:var(--text-muted);font-size:.72rem}.tv-progress{margin-top:auto;padding-top:.8rem}.tv-progress-head{font-size:.74rem;font-weight:700}.tv-progress-head span:last-child{color:#a78bfa}.tv-track{height:6px;border-radius:99px;background:rgba(255,255,255,.08);overflow:hidden;margin-top:.4rem}.tv-track i{display:block;height:100%;background:linear-gradient(90deg,#7c3aed,#a855f7);border-radius:inherit}.tv-empty{padding:2.5rem 1rem;text-align:center;border:1px dashed var(--border);border-radius:18px;color:var(--text-muted)}
.tv-detail-toolbar{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:.9rem 1rem;border-bottom:1px solid var(--border);background:rgba(124,58,237,.035)}.tv-toolbar-title{font-weight:800;font-size:.86rem}.tv-toolbar-sub{font-size:.7rem;color:var(--text-muted);margin-top:.18rem}.tv-add-ep,.tv-add-ep-small{border:1px solid rgba(124,58,237,.35);background:rgba(124,58,237,.12);color:#c4b5fd;border-radius:10px;padding:.58rem .78rem;font-weight:800;cursor:pointer;white-space:nowrap}.tv-add-ep:hover,.tv-add-ep-small:hover{background:rgba(124,58,237,.2)}.tv-complete{border:1px solid rgba(34,197,94,.25);background:rgba(34,197,94,.08);color:#86efac;border-radius:10px;padding:.58rem .78rem;font-size:.72rem;font-weight:800;white-space:nowrap}.tv-ep-row{cursor:pointer}.tv-ep-toggle{width:25px;height:25px;border:1px solid var(--border);border-radius:7px;background:rgba(255,255,255,.03);color:#a78bfa;margin-right:.45rem;transition:transform .18s;cursor:pointer}.tv-ep-row.open .tv-ep-toggle{transform:rotate(90deg)}.tv-ep-details td{padding:0!important;background:rgba(255,255,255,.018)}.tv-ep-detail-inner{padding:1rem;border-top:1px solid rgba(255,255,255,.045)}.tv-detail-loading{color:var(--text-muted);font-size:.75rem;padding:.35rem 0 .8rem}.tv-source-item{display:flex;align-items:center;justify-content:space-between;gap:.8rem;padding:.65rem .7rem;border:1px solid var(--border);border-radius:11px;margin-bottom:.5rem;background:rgba(255,255,255,.018)}.tv-source-main{min-width:0}.tv-source-label{font-weight:800;font-size:.78rem}.tv-source-url{color:var(--text-muted);font-size:.68rem;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;margin-top:.2rem}.tv-source-buttons{display:flex;gap:.4rem;flex:0 0 auto}.tv-source-buttons button{border:1px solid var(--border);background:transparent;color:var(--text-primary);border-radius:8px;padding:.38rem .55rem;font-size:.68rem;cursor:pointer}.tv-source-buttons .danger{color:#fca5a5;border-color:rgba(248,113,113,.25)}.tv-source-actions{display:flex;justify-content:flex-end;padding-top:.2rem}.tv-edit-note{font-size:.68rem;color:var(--text-muted);margin-top:.2rem}.tv-detail{border:1px solid var(--border);border-radius:18px;overflow:hidden;background:rgba(12,14,21,.82)}.tv-detail-head{display:flex;align-items:center;gap:1rem;padding:1rem 1.1rem;border-bottom:1px solid var(--border)}.tv-detail-art{width:62px;height:82px;border-radius:10px;overflow:hidden;background:#111;flex:0 0 auto}.tv-detail-art img{width:100%;height:100%;object-fit:cover}.tv-detail-title{font-size:1.1rem;font-weight:800}.tv-detail-sub{color:var(--text-muted);font-size:.78rem;margin-top:.25rem}.tv-back{margin-left:auto;color:var(--text-muted);text-decoration:none;font-size:.78rem}
.tv-ep-table{width:100%;border-collapse:collapse}.tv-ep-table th,.tv-ep-table td{padding:.78rem 1rem;border-bottom:1px solid rgba(255,255,255,.055);text-align:left;font-size:.8rem}.tv-ep-table th{font-size:.68rem;text-transform:uppercase;color:var(--text-muted);background:rgba(255,255,255,.025)}.tv-source{font-size:.68rem;border-radius:999px;padding:.24rem .48rem;background:rgba(124,58,237,.1);border:1px solid rgba(124,58,237,.18);color:#c4b5fd}.tv-date{white-space:nowrap;color:var(--text-muted)}
.tv-modal{position:fixed;inset:0;z-index:100000;display:none;align-items:center;justify-content:center;padding:1rem;background:rgba(0,0,0,.72);backdrop-filter:blur(8px)}.tv-modal.open{display:flex}.tv-modal-card{width:min(620px,100%);max-height:88vh;overflow:auto;border:1px solid rgba(255,255,255,.1);border-radius:20px;background:#11141d;box-shadow:0 28px 80px rgba(0,0,0,.5)}.tv-modal-head{position:sticky;top:0;display:flex;align-items:center;justify-content:space-between;padding:1rem 1.1rem;border-bottom:1px solid var(--border);background:#11141d}.tv-modal-head h2{margin:0;font-size:1rem}.tv-close{width:34px;height:34px;border-radius:10px;border:1px solid var(--border);background:transparent;color:var(--text-primary);font-size:1.2rem}.tv-modal-body{padding:1.1rem}.tv-form-grid{display:grid;grid-template-columns:1fr 1fr;gap:.8rem}.tv-field{display:grid;gap:.35rem}.tv-field.full{grid-column:1/-1}.tv-field label{font-size:.74rem;font-weight:700;color:var(--text-muted)}.tv-help{font-size:.7rem;color:var(--text-muted)}.tv-actions{display:flex;justify-content:flex-end;gap:.6rem;margin-top:1rem}.tv-cancel{border:1px solid var(--border);background:transparent;color:var(--text-primary);border-radius:10px;padding:.65rem .9rem}.tv-switch{display:flex;align-items:center;gap:.55rem;font-size:.78rem}.tv-switch input{accent-color:#7c3aed}.tv-paste{border:1px solid rgba(124,58,237,.35);background:rgba(124,58,237,.12);color:#c4b5fd;border-radius:10px;padding:0 .78rem;font-weight:800;cursor:pointer;white-space:nowrap}.tv-paste:hover{background:rgba(124,58,237,.2)}
@media(max-width:700px){.tv-folders{grid-template-columns:1fr}.tv-folder-art{width:96px;flex-basis:96px}.tv-form-grid{grid-template-columns:1fr}.tv-field.full{grid-column:auto}.tv-ep-table th:nth-child(3),.tv-ep-table td:nth-child(3){display:none}.tv-add-inner{align-items:flex-start}.tv-add-btn{padding:.6rem .75rem}}@media(max-width:430px){.tv-folder-art{width:82px;flex-basis:82px}.tv-folder-body{padding:.8rem}.tv-detail-art{width:50px;height:68px}.tv-ep-table th,.tv-ep-table td{padding:.65rem .6rem}}
</style><div class="tv-page">
<div class="tv-hero"><h1>🎬 TurboVid Servers</h1><p>Manage AniVault-hosted TurboVid sources by series and episode.</p></div>
<div class="tv-add"><div class="tv-add-inner"><div class="tv-add-copy"><div class="tv-add-icon">＋</div><div><div class="tv-add-title">Add a new series</div><div class="tv-add-sub">Start a folder by adding its first episode source. More episodes can be added anytime.</div></div></div><button class="tv-add-btn" type="button" id="tv-add-series">＋ Add Series</button></div></div>
${selected?`<div class="tv-section-head"><h2>Series / Episodes</h2><span>${selected.episode_count} uploaded episodes</span></div><div class="tv-detail"><div class="tv-detail-head"><div class="tv-detail-art">${selected.image?`<img src="${h(selected.image)}" alt="">`:''}</div><div><div class="tv-detail-title">${h(selected.title)}</div><div class="tv-detail-sub">MAL #${selected.anime_id}${selected.type?` · ${h(selected.type)}`:''}${selected.status?` · ${h(selected.status)}`:''} · ${selected.episode_count}/${selected.totalEps||'?'} episodes</div></div><a class="tv-back" href="${siteUrl}/admin/turbovid_servers.php">← All series</a></div><div class="tv-detail-toolbar"><div><div class="tv-toolbar-title">Episode sources</div><div class="tv-toolbar-sub">Tap an episode to manage its individual servers.</div></div>${selected.totalEps && selected.episode_count >= selected.totalEps ? '<span class="tv-complete">✓ All episodes added</span>' : '<div style="display:flex;gap:.45rem;align-items:center"><button class="tv-add-ep" type="button" id="tv-add-episode">＋ Add Episode</button></div>'}</div><div style="padding:.9rem 1rem;border-bottom:1px solid var(--border)"><div class="tv-progress-head"><span>TurboVid coverage</span><span>${selected.episode_count}/${selected.totalEps||'?'}${selected.totalEps?' · '+Math.round(selected.episode_count/selected.totalEps*100)+'%':''}</span></div><div class="tv-track"><i style="width:${selected.totalEps?Math.min(100,selected.episode_count/selected.totalEps*100):100}%"></i></div></div>${episodes.length?`<div style="overflow:auto"><table class="tv-ep-table"><thead><tr><th>Episode</th><th>Servers</th><th>Sources</th><th>Updated</th></tr></thead><tbody>${epRows}</tbody></table></div>`:'<div class="tv-empty" style="margin:1rem">No active episodes found.</div>'}</div>`:`<div class="tv-section-head"><h2>Your TurboVid Series</h2><span>${series.length} series</span></div>${series.length?`<div class="tv-folders">${cards}</div>`:'<div class="tv-empty">📁<br><strong style="color:var(--text-primary)">No TurboVid series yet</strong><br>Add your first series above.</div>'}`}
</div>
<div class="tv-modal" id="tv-modal"><div class="tv-modal-card"><div class="tv-modal-head"><h2 id="tv-modal-title">Add Series / Episode Source</h2><button class="tv-close" type="button" id="tv-close-modal">×</button></div><div class="tv-modal-body"><form id="tv-form" onsubmit="return saveTurbo(event)"><div class="tv-form-grid">
<input id="tv-source-id" type="hidden" value=""><div class="tv-field"><label>Anime / MAL ID</label><input id="tv-anime" type="number" min="1" class="form-control" value="${selectedAnime||''}" placeholder="e.g. 5114" required><span class="tv-help">The MAL ID used by AniVault.</span></div>
<div class="tv-field"><label>Episode</label><input id="tv-ep" type="number" min="1" class="form-control" placeholder="e.g. 5" required></div>
<div class="tv-field full"><label>Audio group</label><select id="tv-group" class="form-control"><option value="sub">Sub — AV-sub</option><option value="dub">Dub (English) — AV-dub</option><option value="hindi">Dub (Hindi) — AV-hindi</option><option value="multi">Multi Dub — AV-{language}</option></select></div>
<div class="tv-field full" id="tv-lang-wrap" style="display:none"><label>Multi Dub language</label><input id="tv-lang" class="form-control" placeholder="Tamil, Telugu, Spanish…"></div>
<div class="tv-field full"><label>TurboVid embed URL</label><div style="display:flex;gap:.5rem;align-items:stretch"><input id="tv-url" type="url" class="form-control" style="flex:1;min-width:0" placeholder="https://turbovidhls.com/t/..." required><button type="button" class="tv-paste" id="tv-paste-url" title="Paste from clipboard">📋 Paste</button></div></div>
<label class="tv-switch full"><input id="tv-active" type="checkbox" checked> Active source</label></div>
<div class="tv-actions"><button type="button" class="tv-cancel" id="tv-cancel-modal">Cancel</button><button class="tv-save" id="tv-save">Save Source</button></div></form></div></div></div>
<script>
(function(){
const siteUrl=${JSON.stringify(siteUrl)},selectedAnime=${Number(selectedAnime)||0},byId=id=>document.getElementById(id);
let tvPresetEpisode=0;
function closeTurboModal(){const m=byId('tv-modal');if(m)m.classList.remove('open');document.body.style.overflow='';}
function openTurboModal(ep=0,source=null){const m=byId('tv-modal');if(!m)return;tvPresetEpisode=Number(ep||0);m.classList.add('open');document.body.style.overflow='hidden';const f=byId('tv-form'),a=byId('tv-anime'),e=byId('tv-ep');if(f)f.reset();byId('tv-source-id').value='';if(a&&selectedAnime)a.value=String(selectedAnime);if(e&&tvPresetEpisode)e.value=String(tvPresetEpisode);if(source){byId('tv-source-id').value=String(source.id||'');byId('tv-group').value=source.audio_group||'sub';byId('tv-lang').value=source.language||'';byId('tv-url').value=source.embed_url||'';byId('tv-active').checked=!!source.is_active;byId('tv-modal-title').textContent='Edit TurboVid Source';byId('tv-save').textContent='Update Source';}else{byId('tv-active').checked=true;byId('tv-modal-title').textContent='Add Series / Episode Source';byId('tv-save').textContent='Save Source';}const w=byId('tv-lang-wrap');if(w)w.style.display=byId('tv-group').value==='multi'?'':'none';}
async function loadTurboSources(ep){const box=document.querySelector('#tv-ep-details-'+ep+' .tv-detail-loading');if(!box)return;try{const r=await fetch(siteUrl+'/admin/turbovid_servers.php?json=1&anime='+encodeURIComponent(selectedAnime)+'&episode='+encodeURIComponent(ep));const d=await r.json();if(!d.success)throw new Error(d.error||'Load failed');box.innerHTML='';if(!d.sources.length){box.innerHTML='<div class="tv-detail-loading">No sources found.</div>';return;}d.sources.forEach(src=>{const item=document.createElement('div');item.className='tv-source-item';const main=document.createElement('div');main.className='tv-source-main';const label=document.createElement('div');label.className='tv-source-label';label.textContent=String(src.label||'Source')+(src.is_active?'':' · Inactive');const note=document.createElement('div');note.className='tv-edit-note';note.textContent=String(src.audio_group||'')+(src.language?' · '+src.language:'');const url=document.createElement('div');url.className='tv-source-url';url.textContent=String(src.embed_url||'');main.append(label,note,url);const actions=document.createElement('div');actions.className='tv-source-buttons';const edit=document.createElement('button');edit.type='button';edit.textContent='Edit';edit.onclick=e=>{e.stopPropagation();openTurboModal(src.episode_num,src);};const del=document.createElement('button');del.type='button';del.className='danger';del.textContent='Delete';del.onclick=e=>{e.stopPropagation();deleteTurboSource(src.id);};actions.append(edit,del);item.append(main,actions);box.appendChild(item);});}catch(err){box.innerHTML='<div style="color:#fca5a5;font-size:.75rem">Could not load source details.</div>';}}
async function toggleTurboEpisode(row){const ep=Number(row?.dataset?.episode||0),d=byId('tv-ep-details-'+ep);if(!d)return;const wasOpen=!d.hidden;document.querySelectorAll('.tv-ep-details').forEach(x=>x.hidden=true);document.querySelectorAll('.tv-ep-row').forEach(x=>x.classList.remove('open'));if(wasOpen)return;d.hidden=false;row.classList.add('open');const box=d.querySelector('.tv-detail-loading');if(box)box.textContent='Loading sources…';await loadTurboSources(ep);}
async function deleteTurboSource(id){if(!confirm('Delete this TurboVid source?'))return;try{const r=await fetch(siteUrl+'/admin/turbovid_servers.php?id='+encodeURIComponent(id),{method:'DELETE'});const d=await r.json();if(!d.success)throw new Error(d.error||'Delete failed');location.reload();}catch(err){alert(err.message||'Delete failed');}}
async function saveTurbo(e){e.preventDefault();const id=+byId('tv-source-id').value||0,anime_id=+byId('tv-anime').value,episode_num=+byId('tv-ep').value,audio_group=byId('tv-group').value,language=byId('tv-lang').value.trim(),embed_url=byId('tv-url').value.trim(),is_active=byId('tv-active').checked?1:0;if(!anime_id||!episode_num||!embed_url||(audio_group==='multi'&&!language))return false;const b=byId('tv-save');b.disabled=true;b.textContent=id?'Updating…':'Saving…';try{const r=await fetch(siteUrl+'/admin/turbovid_servers.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,anime_id,episode_num,audio_group,language,embed_url,is_active})});const d=await r.json();if(!d.success)throw new Error(d.error||'Save failed');location.href=siteUrl+'/admin/turbovid_servers.php?anime='+anime_id;}catch(err){alert(err.message||'Save failed');b.disabled=false;b.textContent=id?'Update Source':'Save Source';}return false;}
const tvGroup=byId('tv-group');tvGroup?.addEventListener('change',()=>{const w=byId('tv-lang-wrap');if(w)w.style.display=tvGroup.value==='multi'?'':'none';});
byId('tv-add-series')?.addEventListener('click',()=>openTurboModal());byId('tv-add-episode')?.addEventListener('click',()=>{const nums=${JSON.stringify(episodes.map(e=>Number(e.episode_num)).filter(n=>n>0))};const next=nums.length?Math.max(...nums)+1:1;openTurboModal(next);});byId('tv-close-modal')?.addEventListener('click',closeTurboModal);byId('tv-cancel-modal')?.addEventListener('click',closeTurboModal);byId('tv-modal')?.addEventListener('click',e=>{if(e.target.id==='tv-modal')closeTurboModal();});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeTurboModal();});
document.querySelectorAll('[data-tv-expand="1"]').forEach(el=>el.addEventListener('click',e=>{e.stopPropagation();const row=el.closest('.tv-ep-row');if(row)toggleTurboEpisode(row);}));document.querySelectorAll('[data-tv-add-episode]').forEach(el=>el.addEventListener('click',e=>{e.stopPropagation();openTurboModal(Number(el.dataset.tvAddEpisode||0));}));

byId('tv-form')?.addEventListener('submit',saveTurbo);byId('tv-paste-url')?.addEventListener('click',async()=>{const input=byId('tv-url');if(!input)return;try{if(!navigator.clipboard?.readText)throw new Error('Clipboard access is unavailable in this browser.');const text=await navigator.clipboard.readText();if(!text.trim())throw new Error('Clipboard is empty.');input.value=text.trim();input.focus();input.dispatchEvent(new Event('input',{bubbles:true}));}catch(err){alert(err.message||'Could not paste from clipboard. You can paste manually.');}});window.openTurboModal=openTurboModal;window.closeTurboModal=closeTurboModal;
})();
</script>`;
}
