/**
 * Emits exact player state to a companion/extension without ever touching
 * Discord directly from the browser page.
 *
 * The HTMLVideoElement is the source of truth. The bridge always derives
 * timestamps from currentTime instead of incrementing a local counter, so
 * seeks, pauses and buffering cannot accumulate clock drift.
 */
export function discordPresenceScript(params: {
  animeId: number;
  title: string;
  image: string;
  epNum: number;
  episodeTitle: string | null;
  durationSec: number;
  siteUrl: string;
}): string {
  const payload = JSON.stringify({
    animeId: params.animeId,
    title: params.title,
    image: params.image,
    episode: params.epNum,
    episodeTitle: params.episodeTitle,
    duration: params.durationSec,
    url: `${params.siteUrl}/watch?anime=${params.animeId}&ep=${params.epNum}`,
  }).replace(/</g, '\\u003c');

  return `<script>
(function(){
'use strict';

const META = ${payload};
const video = document.getElementById('sp-video');
if (!video) return;

const BRIDGE_EVENT = 'anivault:discord-presence';
let syncTimer = null;
let pendingSeek = false;
let lastSent = '';

function finite(n){ return Number.isFinite(n) && n >= 0 ? n : 0; }

function snapshot(eventName){
  const current = finite(video.currentTime);
  const duration = finite(video.duration) || finite(META.duration);
  const playing = !video.paused && !video.ended && !video.seeking && !video.readyState || (!video.paused && !video.ended && !video.seeking);

  const detail = {
    version: 1,
    source: 'anivault-player',
    event: eventName,
    animeId: META.animeId,
    title: META.title,
    image: META.image,
    episode: META.episode,
    episodeTitle: META.episodeTitle,
    url: META.url,
    currentTime: current,
    duration,
    playing,
    ended: video.ended,
    at: Date.now(),
  };

  // The extension/companion listens for this event. postMessage is also sent
  // so an MV3 content script can receive the event without page-world access.
  window.dispatchEvent(new CustomEvent(BRIDGE_EVENT, { detail }));
  window.postMessage({ type: BRIDGE_EVENT, detail }, '*');
}

function send(eventName){
  const current = Math.round(finite(video.currentTime) * 1000);
  const duration = Math.round((finite(video.duration) || finite(META.duration)) * 1000);
  const key = eventName + ':' + current + ':' + duration + ':' + video.paused + ':' + video.ended;
  if (eventName === 'timeupdate' && key === lastSent) return;
  lastSent = key;
  snapshot(eventName);
}

function startSync(){
  stopSync();
  // This is deliberately a re-read of video.currentTime, not a local counter.
  // Discord timestamps are generated by the companion from this exact value.
  syncTimer = window.setInterval(function(){
    if (!video.paused && !video.ended && !video.seeking) send('sync');
  }, 1000);
}

function stopSync(){
  if (syncTimer !== null) {
    window.clearInterval(syncTimer);
    syncTimer = null;
  }
}

video.addEventListener('play', function(){
  send('play');
  startSync();
});

video.addEventListener('playing', function(){
  send('playing');
  startSync();
});

video.addEventListener('pause', function(){
  stopSync();
  send('pause');
});

video.addEventListener('waiting', function(){
  // Stop the remote clock immediately. When playback resumes, a fresh
  // timestamp is calculated from the actual currentTime.
  stopSync();
  send('waiting');
});

video.addEventListener('stalled', function(){
  stopSync();
  send('stalled');
});

video.addEventListener('seeking', function(){
  pendingSeek = true;
  stopSync();
});

video.addEventListener('seeked', function(){
  if (!pendingSeek) return;
  pendingSeek = false;
  send('seeked');
  if (!video.paused && !video.ended) startSync();
});

video.addEventListener('loadedmetadata', function(){ send('metadata'); });
video.addEventListener('durationchange', function(){ send('durationchange'); });
video.addEventListener('timeupdate', function(){ send('timeupdate'); });
video.addEventListener('ended', function(){
  stopSync();
  send('ended');
});

// The page may already have metadata by the time this script runs.
window.setTimeout(function(){ send('ready'); }, 0);

window.addEventListener('pagehide', function(){
  stopSync();
  send('pagehide');
});
})();
</script>`;
}
